# name: Mirroring

# on: [push, delete]

# jobs:
#   to_gitlab:
#     runs-on: ubuntu-latest
#     steps:                                              # <-- must use actions/checkout before mirroring!
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - uses: pixta-dev/repository-mirroring-action@v1.1.0
#         with:
#           target_repo_url:
#             git@git.swmgit.org:swm-13-main/13_swm29/test.git
#           ssh_private_key:                              # <-- use 'secrets' to pass credential information.
#             ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}


name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git.swmgit.org/swm-13-main/13_swm29/test.git"
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "jh981113"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} // Generate here: https://gitlab.com/profile/personal_access_tokens
        GITLAB_PROJECT_ID: "https://git.swmgit.org/swm-13-main/13_swm29/test.git/edit" // https://gitlab.com/<namespace>/<repository>/edit
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} // https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
